name: Cypress Tests with JSON Cache

on: [push]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore previous run JSON
        id: cache-previous-run-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{github.workspace}}/previousRun.json
          key: ${{ runner.os }}-previousRun

      - name: Cypress run with cached JSON
        id: cypress-run
        uses: cypress-io/github-action@v4
        with:
          # Adjust the start and wait-on commands as needed for your project
          start: npm start
          wait-on: "http://localhost:3000"
          # Provide the path to the cached JSON as an environment variable
        env:
          CYPRESS_PREV_RUN_JSON: "${{github.workspace}}/previousRun.json"

      - name: Save Primes
        id: cache-previous-run-save
        uses: actions/cache/save@v4
        with:
          path: |
            ${{github.workspace}}/previousRun.json
          key: ${{ steps.cache-previous-run-restore.outputs.cache-primary-key }}
