name: Cypress Workflow with Caching

on:
  push:

jobs:
  cypress_tests:
    runs-on: ubuntu-latest # Or your preferred OS

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Example version, adjust as needed

      - name: Install dependencies
        run: npm ci

      # Cache the 'previousRun.json' (if it exists)
      - name: Retrieve previousRun.json from cache
        uses: actions/cache@v3
        with:
          path: ./previousRun.json
          key: ${{ runner.os }}-previous-run-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-previous-run-

      # Run Cypress tests with enhanced script
      - name: Run Cypress Tests
        run: npm run cypress:run # Assuming you have 'cypress:run' defined

      # Update cache only if 'previousRun.json' has changed
      - name: Update previousRun.json in cache
        uses: actions/cache@v3
        if: ${{ hashFiles('./previousRun.json') != '' }} # Check for changes
        with:
          path: ./previousRun.json
          key: ${{ runner.os }}-previous-run-${{ hashFiles('package-lock.json') }}
